'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class fuelTankRec

    '''<summary>
    '''MainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainMenu As Global.DevExpress.Web.ASPxMenu

    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''dtpSearchDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpSearchDateFrom As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''dtpSearchDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpSearchDateTo As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''cboSiteSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteSearch As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmdSearcByDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSearcByDate As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdViewReceiptReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdViewReceiptReport As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''SqlDataSourceSearchSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSearchSite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ASPxFormLayout2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout2 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''GridViewReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewReceipt As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdView As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''popupAddReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAddReceipt As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''cbpLoadDataAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbpLoadDataAdd As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''ASPxFormLayout10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout10 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''dtpReceiptDateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpReceiptDateAdd As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''cboSiteAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cboTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTankAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceTanks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTanks As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtQuantityAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtUnitPriceAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitPriceAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtShortageAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShortageAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtOverAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtNetQuantityAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetQuantityAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtAmountAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtInvoiceNumberAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNumberAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtVehicleNumberAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehicleNumberAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTransporterAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransporterAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtDriverAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDriverAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtRemarksAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarksAdd As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''cmdSubmitAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout6 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblNCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNCount As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtTransactionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransactionCode As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupViewReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupViewReceipt As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''cbpView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbpView As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''ASPxFormLayout11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout11 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelete As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''txtReceiptDateView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptDateView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteNameView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTankView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTankView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtQuantityView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityView As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtUnitPriceView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitPriceView As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtShortageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShortageView As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtOverView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverView As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtNetQuantityView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetQuantityView As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtAmountView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountView As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtInvoiceNumberView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNumberView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtVehicleNumberView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehicleNumberView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTransporterView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransporterView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtDriverView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDriverView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtRemarksView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarksView As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''lblErrMsgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtReceiptIDView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptIDView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupEditReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupEditReceipt As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout12 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''dtpReceiptDateEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpReceiptDateEdit As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''cboSiteEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cboTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTankEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceTanksEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTanksEdit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtQuantityEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityEdit As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtUnitPriceEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitPriceEdit As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtShortageEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShortageEdit As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtOverEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverEdit As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtNetQuantityEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetQuantityEdit As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtAmountEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountEdit As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtInvoiceNumberEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNumberEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtVehicleNumberEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehicleNumberEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTransporterEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransporterEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtDriverEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDriverEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtRemarksEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarksEdit As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''cmdSubmitEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout13 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtReceiptIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTankIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTankIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''PopupErrMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupErrMsg As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout4 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''lblErrMsgGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgGen As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cmdErrMsgCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdErrMsgCancel As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout9 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdConfirmDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdConfirmDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtSiteSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteSearch As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSearchDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchDateFrom As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSearchDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchDateTo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''SqlDataSourceReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceReceipt As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceSites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSites As Global.System.Web.UI.WebControls.SqlDataSource
End Class
