'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class accountSetup

    '''<summary>
    '''MainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainMenu As Global.DevExpress.Web.ASPxMenu

    '''<summary>
    '''FilterPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilterPanel As Global.DevExpress.Web.ASPxPanel

    '''<summary>
    '''SearchButtonEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchButtonEdit As Global.DevExpress.Web.ASPxButtonEdit

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cbpList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbpList As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''ASPxFormLayout2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout2 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''GridViewAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAccounts As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''popupAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''FormLayoutAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormLayoutAdd As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cboAccountTypeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAccountTypeAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtAccountCodeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountCodeAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAccountNameAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNameAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAccountDescriptionAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountDescriptionAdd As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''cboBankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBankAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtBankAccountNumberAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankAccountNumberAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtBankBranchAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankBranchAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboMobileOperatorAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMobileOperatorAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtMobileNumberAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMobileNumberAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''dtpBalanceDateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpBalanceDateAdd As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''cboBalanceTypeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBalanceTypeAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtBalanceAmountAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBalanceAmountAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''GridViewAccountSiteAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAccountSiteAdd As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdSubmitAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout6 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtTransactionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransactionCode As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupView As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''FormLayoutView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormLayoutView As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdEditAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditAccount As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdEditSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditSite As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdDeleteAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteAccount As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblAccountTypeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountTypeView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblAccountCodeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountCodeView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblAccountNameView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountNameView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblAccountDescriptionView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountDescriptionView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblBankView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBankView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblBankAccountNumberView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBankAccountNumberView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblBankBranchView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBankBranchView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblMobileOperatorView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMobileOperatorView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblMobileNumberView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMobileNumberView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''GridViewAccountSiteView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAccountSiteView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''lblErrMsgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''popupEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''cbpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbpEdit As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''FormLayoutEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormLayoutEdit As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cboAccountTypeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAccountTypeEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtAccountCodeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountCodeEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAccountNameEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNameEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAccountDescriptionEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountDescriptionEdit As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''cboBankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBankEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtBankAccountNumberEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankAccountNumberEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtBankBranchEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankBranchEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboMobileOperatorEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMobileOperatorEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtMobileNumberEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMobileNumberEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmdSubmitEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout7 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtAccountIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''PopupConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''lblAccountDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtAccountIDDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountIDDelete As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmdDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''popupAssignSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAssignSite As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''cbpAssignSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbpAssignSite As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''cbpUnAssignSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbpUnAssignSite As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''ASPxFormLayout3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout3 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''GridViewSiteUnassigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSiteUnassigned As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''GridViewSiteAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSiteAssigned As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''lblErrMsgAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgAssign As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccessMsgAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgAssign As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtItemID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemID As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAccountIDView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountIDView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''SqlDataSourceUnassignedSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceUnassignedSite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceAssignedSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAssignedSite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAccounts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceAccountType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAccountType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceBank As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceMobileMoney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceMobileMoney As Global.System.Web.UI.WebControls.SqlDataSource
End Class
