'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class fuelSetup

    '''<summary>
    '''MainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainMenu As Global.DevExpress.Web.ASPxMenu

    '''<summary>
    '''ASPxFormLayout2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout2 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cboSiteSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteSearch As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceSearchSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSearchSite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''ASPxPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControl1 As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''ASPxFormLayout3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout3 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdAddProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddProduct As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridViewProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewProduct As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdEditProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditProduct As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''cmdDeleteProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteProduct As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''ASPxFormLayout5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout5 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdAddSiteProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddSiteProduct As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridViewSiteProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSiteProduct As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdDeleteSiteProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteSiteProduct As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''ASPxFormLayout12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout12 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdAddRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddRate As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridViewRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewRate As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdDeleteSiteRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteSiteRate As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''ASPxFormLayout17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout17 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdAddTank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddTank As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridViewTank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewTank As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdEditTank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditTank As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''cmdDeleteTank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteTank As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''ASPxFormLayout20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout20 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdAddPump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddPump As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridViewPump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewPump As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdEditPump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditPump As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''cmdDeletePump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeletePump As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''ASPxFormLayout25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout25 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdAddAttendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddAttendant As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridViewAttendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAttendant As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdViewAttendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdViewAttendant As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''cmdEditAttendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditAttendant As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''cmdDeleteAttendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteAttendant As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''popupProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupProductAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout4 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtProductCodeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductCodeAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtProductNameAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductNameAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmdSubmitProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitProductAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshProductAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveProductAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout6 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesProductAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoProductAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgProductAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgProductAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''popupProductEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupProductEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout7 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtProductCodeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductCodeEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtProductNameEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductNameEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmdSubmitProductEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitProductEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveProductEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveProductEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout8 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesProductEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesProductEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoProductEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoProductEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgProductEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgProductEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgProductEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgProductEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtProductIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupProductDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupProductDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout9 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdConfirmProductDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmProductDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdConfirmProductDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmProductDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgProductDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgProductDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgProductDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgProductDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtProductIDDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductIDDelete As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupSiteProductAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout10 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteNameSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameSiteProductAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDSiteProductAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboSiteProductProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteProductProductAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmdSubmitSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitSiteProductAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshSiteProductAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveSiteProductAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout11 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesSiteProductAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoSiteProductAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgSiteProductAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgSiteProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgSiteProductAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''popupSiteProductDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupSiteProductDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout28 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdConfirmSiteProductDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmSiteProductDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdConfirmSiteProductDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmSiteProductDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgSiteProductDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgSiteProductDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgSiteProductDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgSiteProductDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtSiteProductIDDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteProductIDDelete As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupRateAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout13 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteNameRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameRateAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDRateAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboRateProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRateProductAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''dtpRateDateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpRateDateAdd As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''txtSellingPriceRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSellingPriceRateAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtCostPriceRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCostPriceRateAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''cmdSubmitRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitRateAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshRateAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveRateAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout14 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesRateAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoRateAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgRateAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgRateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgRateAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''popupTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTankAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout15 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteNameTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameTankAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDTankAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboTankProductAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTankProductAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtTankCodeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTankCodeAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTankCapacityAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTankCapacityAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''cmdSubmitTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitTankAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshTankAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveTankAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout16 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesTankAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoTankAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgTankAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgTankAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''popupTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTankEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout18 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteNameTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameTankEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDTankEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboTankProductEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTankProductEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtTankCodeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTankCodeEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTankCapacityEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTankCapacityEdit As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''chkTankDisableEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTankDisableEdit As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''cmdSubmitTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitTankEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshTankEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveTankEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout19 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesTankEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoTankEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgTankEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgTankEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtTankIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTankIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupTankDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTankDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout29 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdConfirmTankDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmTankDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdConfirmTankDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmTankDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgTankDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgTankDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgTankDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgTankDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtTankIDDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTankIDDelete As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupPumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupPumpAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout21 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteNamePumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNamePumpAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDPumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDPumpAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboPumpTankAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPumpTankAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtPumpCodeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPumpCodeAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmdSubmitPumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitPumpAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshPumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshPumpAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSavePumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSavePumpAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout22 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesPumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesPumpAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoPumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoPumpAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgPumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgPumpAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgPumpAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgPumpAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''popupPumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupPumpEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout23 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteNamePumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNamePumpEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDPumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDPumpEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboPumpTankEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPumpTankEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtPumpCodeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPumpCodeEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''chkPumpDisableEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPumpDisableEdit As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''cmdSubmitPumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitPumpEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshPumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshPumpEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSavePumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSavePumpEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout24 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesPumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesPumpEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoPumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoPumpEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgPumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgPumpEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgPumpEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgPumpEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtPumpIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPumpIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupPumpDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupPumpDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout30 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdConfirmPumpDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmPumpDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdConfirmPumpDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmPumpDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgPumpDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgPumpDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgPumpDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgPumpDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtPumpIDDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPumpIDDelete As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupAttendantView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAttendantView As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout31 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdPrintAttendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPrintAttendant As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''picPictureView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents picPictureView As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''txtAttendantIDView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttendantIDView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteNameAttendantView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameAttendantView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDAttendantView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDAttendantView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtStaffIDView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStaffIDView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtFirstNameView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstNameView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtOtherNamesView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherNamesView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtGenderView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGenderView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtDateOfBirthView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateOfBirthView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAddressView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressView As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtPhoneNumber1View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneNumber1View As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtPhoneNumber2View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneNumber2View As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactNameView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactNameView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactRelationView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactRelationView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactAddressView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactAddressView As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtContactPhoneNumberView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPhoneNumberView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupAttendantDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAttendantDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout34 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdConfirmAttendantDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmAttendantDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdConfirmAttendantDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmAttendantDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgAttendantDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgAttendantDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgAttendantDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgAttendantDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtAttendantIDDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttendantIDDelete As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAttendantAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout26 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteNameAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameAttendantAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDAttendantAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtStaffIDAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStaffIDAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtFirstNameAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstNameAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtOtherNamesAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherNamesAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboGenderAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGenderAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''dtpDateOfBirthAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpDateOfBirthAdd As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''txtAddressAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressAdd As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtPhoneNumber1Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneNumber1Add As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtPhoneNumber2Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneNumber2Add As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactNameAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactNameAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactRelationAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactRelationAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactAddressAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactAddressAdd As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtContactPhoneNumberAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPhoneNumberAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''picPictureAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents picPictureAdd As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''FileUploadPictureAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadPictureAdd As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''dtpBalanceDateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpBalanceDateAdd As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''cboBalanceTypeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBalanceTypeAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceBalanceTypeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceBalanceTypeAdd As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtBalanceAmountAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBalanceAmountAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''cmdSubmitAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitAttendantAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshAttendantAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveAttendantAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout27 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesAttendantAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoAttendantAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgAttendantAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgAttendantAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtAttendantTransactionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttendantTransactionCode As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAttendantEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout32 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cboSiteAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteAttendantEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblAttendantIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAttendantIDEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtStaffIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStaffIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtFirstNameEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstNameEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtOtherNamesEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherNamesEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cboGenderEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGenderEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''dtpDateOfBirthEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpDateOfBirthEdit As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''txtAddressEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressEdit As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtPhoneNumber1Edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneNumber1Edit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtPhoneNumber2Edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneNumber2Edit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactNameEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactNameEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactRelationEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactRelationEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtContactAddressEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactAddressEdit As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtContactPhoneNumberEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPhoneNumberEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''chkAttendantDisableEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAttendantDisableEdit As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''picPictureEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents picPictureEdit As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''FileUploadPictureEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadPictureEdit As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''cmdSubmitAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitAttendantEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshAttendantEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveAttendantEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout33 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesAttendantEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoAttendantEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgAttendantEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgAttendantEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtAttendantIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttendantIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAttendantIDEdit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttendantIDEdit1 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAttendantID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttendantID As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteSearch As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''SqlDataSourceProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceProduct As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceSiteFuelProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSiteFuelProduct As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRate As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceTank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTank As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourcePump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePump As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceAttendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAttendant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceSiteAttendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSiteAttendant As Global.System.Web.UI.WebControls.SqlDataSource
End Class
