'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class siteSetup

    '''<summary>
    '''MainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainMenu As Global.DevExpress.Web.ASPxMenu

    '''<summary>
    '''FilterPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilterPanel As Global.DevExpress.Web.ASPxPanel

    '''<summary>
    '''SearchButtonEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchButtonEdit As Global.DevExpress.Web.ASPxButtonEdit

    '''<summary>
    '''ASPxFormLayout2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout2 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''GridViewSites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSites As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''popupAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout3 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteCodeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteCodeAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''dtpRegDateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpRegDateAdd As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''txtSiteNameAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAddressAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressAdd As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtCompanyAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyAdd As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtBusinessInfoAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusinessInfoAdd As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''cmdSubmitAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout6 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''popupEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout7 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtSiteCodeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteCodeEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''dtpRegDateEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpRegDateEdit As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''txtSiteNameEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAddressEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressEdit As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtCompanyEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtBusinessInfoEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusinessInfoEdit As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''cmdSubmitEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout8 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtSiteIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''PopupConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''lblSiteDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiteDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtSiteIDDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDDelete As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmdDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgDelete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccessMsgDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgDelete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SqlDataSourceSites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSites As Global.System.Web.UI.WebControls.SqlDataSource
End Class
