'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FuelAttendShort

    '''<summary>
    '''MainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainMenu As Global.DevExpress.Web.ASPxMenu

    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''dtpSearchDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpSearchDateFrom As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''dtpSearchDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpSearchDateTo As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''cboSiteSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteSearch As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmdSearcByDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSearcByDate As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdViewSalesReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdViewSalesReport As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''SqlDataSourceSearchSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSearchSite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ASPxFormLayout2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout2 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''GridViewSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSales As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''cmdView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdView As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''popupAddSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupAddSales As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout3 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''dtpSalesDateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpSalesDateAdd As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''cboSiteAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cboAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAttendantAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceAttendantAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAttendantAdd As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtAmountAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountAdd As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtRemarkAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarkAdd As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''cmdSubmitAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveAdd As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout6 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgAdd As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtTransactionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransactionCode As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupViewSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupViewSales As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout10 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelete As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''txtSalesDateView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesDateView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteNameView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteNameView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAttendantView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttendantView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtAmountView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountView As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtRemarkView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarkView As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''lblErrMsgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgView As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtSalesIDView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesIDView As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''popupEditSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupEditSales As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout11 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''dtpSalesDateEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpSalesDateEdit As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''cboSiteEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSiteEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cboAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAttendantEdit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceAttendantEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAttendantEdit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtAmountEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountEdit As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''txtRemarkEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarkEdit As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''cmdSubmitEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdRefreshEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmSaveEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmSaveEdit As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout12 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdSaveYesEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveYesEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdSaveNoEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveNoEdit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgEdit As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtSalesIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSiteIDEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteIDEdit As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''PopupErrMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupErrMsg As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout4 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''lblErrMsgGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgGen As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cmdErrMsgCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdErrMsgCancel As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopupConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupConfirmDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxFormLayout9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout9 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmdConfirmDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmDeleteYes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmdConfirmDeleteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmDeleteNo As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblErrMsgDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrMsgDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSuccessMsgDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMsgDelete As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtSiteSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSiteSearch As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSearchDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchDateFrom As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSearchDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchDateTo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''SqlDataSourceSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSales As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceSites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSites As Global.System.Web.UI.WebControls.SqlDataSource
End Class
