Module modUserRoles

    Public intRoleID1 As Boolean
    Public intRoleID2 As Boolean
    Public intRoleID3 As Boolean
    Public intRoleID4 As Boolean
    Public intRoleID5 As Boolean
    Public intRoleID6 As Boolean
    Public intRoleID7 As Boolean
    Public intRoleID8 As Boolean
    Public intRoleID9 As Boolean
    Public intRoleID10 As Boolean
    Public intRoleID11 As Boolean
    Public intRoleID12 As Boolean
    Public intRoleID13 As Boolean
    Public intRoleID14 As Boolean
    Public intRoleID15 As Boolean
    Public intRoleID16 As Boolean
    Public intRoleID17 As Boolean
    Public intRoleID18 As Boolean
    Public intRoleID19 As Boolean
    Public intRoleID20 As Boolean
    Public intRoleID21 As Boolean
    Public intRoleID22 As Boolean
    Public intRoleID23 As Boolean
    Public intRoleID24 As Boolean
    Public intRoleID25 As Boolean
    Public intRoleID26 As Boolean
    Public intRoleID27 As Boolean
    Public intRoleID28 As Boolean
    Public intRoleID29 As Boolean
    Public intRoleID30 As Boolean
    Public intRoleID31 As Boolean
    Public intRoleID32 As Boolean
    Public intRoleID33 As Boolean
    Public intRoleID34 As Boolean
    Public intRoleID35 As Boolean
    Public intRoleID36 As Boolean
    Public intRoleID37 As Boolean
    Public intRoleID38 As Boolean
    Public intRoleID39 As Boolean
    Public intRoleID40 As Boolean
    Public intRoleID41 As Boolean
    Public intRoleID42 As Boolean
    Public intRoleID43 As Boolean
    Public intRoleID44 As Boolean
    Public intRoleID45 As Boolean
    Public intRoleID46 As Boolean
    Public intRoleID47 As Boolean
    Public intRoleID48 As Boolean
    Public intRoleID49 As Boolean
    Public intRoleID50 As Boolean
    Public intRoleID51 As Boolean
    Public intRoleID52 As Boolean
    Public intRoleID53 As Boolean
    Public intRoleID54 As Boolean
    Public intRoleID55 As Boolean
    Public intRoleID56 As Boolean
    Public intRoleID57 As Boolean
    Public intRoleID58 As Boolean
    Public intRoleID59 As Boolean
    Public intRoleID60 As Boolean
    Public intRoleID61 As Boolean
    Public intRoleID62 As Boolean
    Public intRoleID63 As Boolean
    Public intRoleID64 As Boolean
    Public intRoleID65 As Boolean
    Public intRoleID66 As Boolean
    Public intRoleID67 As Boolean
    Public intRoleID68 As Boolean
    Public intRoleID69 As Boolean
    Public intRoleID70 As Boolean
    Public intRoleID71 As Boolean
    Public intRoleID72 As Boolean
    Public intRoleID73 As Boolean
    Public intRoleID74 As Boolean
    Public intRoleID75 As Boolean
    Public intRoleID76 As Boolean
    Public intRoleID77 As Boolean
    Public intRoleID78 As Boolean
    Public intRoleID79 As Boolean
    Public intRoleID80 As Boolean
    Public intRoleID81 As Boolean
    Public intRoleID82 As Boolean
    Public intRoleID83 As Boolean
    Public intRoleID84 As Boolean
    Public intRoleID85 As Boolean
    Public intRoleID86 As Boolean
    Public intRoleID87 As Boolean
    Public intRoleID88 As Boolean
    Public intRoleID89 As Boolean
    Public intRoleID90 As Boolean
    Public intRoleID91 As Boolean
    Public intRoleID92 As Boolean
    Public intRoleID93 As Boolean
    Public intRoleID94 As Boolean
    Public intRoleID95 As Boolean
    Public intRoleID96 As Boolean
    Public intRoleID97 As Boolean
    Public intRoleID98 As Boolean
    Public intRoleID99 As Boolean
    Public intRoleID100 As Boolean
    Public intRoleID101 As Boolean
    Public intRoleID102 As Boolean
    Public intRoleID103 As Boolean
    Public intRoleID104 As Boolean
    Public intRoleID105 As Boolean
    Public intRoleID106 As Boolean
    Public intRoleID107 As Boolean
    Public intRoleID108 As Boolean
    Public intRoleID109 As Boolean
    Public intRoleID110 As Boolean
    Public intRoleID111 As Boolean
    Public intRoleID112 As Boolean
    Public intRoleID113 As Boolean
    Public intRoleID114 As Boolean
    Public intRoleID115 As Boolean
    Public intRoleID116 As Boolean
    Public intRoleID117 As Boolean
    Public intRoleID118 As Boolean
    Public intRoleID119 As Boolean
    Public intRoleID120 As Boolean
    Public intRoleID121 As Boolean
    Public intRoleID122 As Boolean
    Public intRoleID123 As Boolean
    Public intRoleID124 As Boolean
    Public intRoleID125 As Boolean
    Public intRoleID126 As Boolean
    Public intRoleID127 As Boolean
    Public intRoleID128 As Boolean
    Public intRoleID129 As Boolean
    Public intRoleID130 As Boolean
    Public intRoleID131 As Boolean
    Public intRoleID132 As Boolean
    Public intRoleID133 As Boolean
    Public intRoleID134 As Boolean
    Public intRoleID135 As Boolean
    Public intRoleID136 As Boolean
    Public intRoleID137 As Boolean
    Public intRoleID138 As Boolean
    Public intRoleID139 As Boolean
    Public intRoleID140 As Boolean
    Public intRoleID141 As Boolean
    Public intRoleID142 As Boolean
    Public intRoleID143 As Boolean
    Public intRoleID144 As Boolean
    Public intRoleID145 As Boolean
    Public intRoleID146 As Boolean
    Public intRoleID147 As Boolean
    Public intRoleID148 As Boolean
    Public intRoleID149 As Boolean
    Public intRoleID150 As Boolean
    Public intRoleID151 As Boolean
    Public intRoleID152 As Boolean
    Public intRoleID153 As Boolean
    Public intRoleID154 As Boolean
    Public intRoleID155 As Boolean
    Public intRoleID156 As Boolean
    Public intRoleID157 As Boolean
    Public intRoleID158 As Boolean
    Public intRoleID159 As Boolean
    Public intRoleID160 As Boolean
    Public intRoleID161 As Boolean
    Public intRoleID162 As Boolean
    Public intRoleID163 As Boolean
    Public intRoleID164 As Boolean
    Public intRoleID165 As Boolean
    Public intRoleID166 As Boolean
    Public intRoleID167 As Boolean
    Public intRoleID168 As Boolean
    Public intRoleID169 As Boolean
    Public intRoleID170 As Boolean
    Public intRoleID171 As Boolean
    Public intRoleID172 As Boolean
    Public intRoleID173 As Boolean
    Public intRoleID174 As Boolean
    Public intRoleID175 As Boolean
    Public intRoleID176 As Boolean
    Public intRoleID177 As Boolean
    Public intRoleID178 As Boolean
    Public intRoleID179 As Boolean
    Public intRoleID180 As Boolean
    Public intRoleID181 As Boolean
    Public intRoleID182 As Boolean
    Public intRoleID183 As Boolean
    Public intRoleID184 As Boolean
    Public intRoleID185 As Boolean
    Public intRoleID186 As Boolean
    Public intRoleID187 As Boolean
    Public intRoleID188 As Boolean
    Public intRoleID189 As Boolean
    Public intRoleID190 As Boolean
    Public intRoleID191 As Boolean
    Public intRoleID192 As Boolean
    Public intRoleID193 As Boolean
    Public intRoleID194 As Boolean
    Public intRoleID195 As Boolean
    Public intRoleID196 As Boolean
    Public intRoleID197 As Boolean
    Public intRoleID198 As Boolean
    Public intRoleID199 As Boolean
    Public intRoleID200 As Boolean

    Public dtTempUserRole As DataTable, dtAllUserRoles As DataTable
End Module
